version: "2"
services:
  postman_checks:
      container_name: kk_sample_api_test
      build: .
      image: postman_checks
      command:
        run com.kk.sample.postman.api.postman_collection.json 
        -e environments/host-fakejson.postman_environment.json 
        -r html,cli 
        --reporter-html-export reports/kk_sample_api_test.html 
        --reporter-html-template reports/templates/customTemplate.hbs
      volumes:
        - ./src:/etc/newman